-- Enable Row Level Security on all tables
-- Agent Brain uses service_role key which bypasses RLS,
-- so this adds defense-in-depth without affecting functionality.

-- Enable RLS on all public tables
ALTER TABLE IF EXISTS settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS folder_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS mailbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orchestrator_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orchestrator_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS permission_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS project_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS memory_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS summary_consolidation_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS remote_commands ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_monitor_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_monitor_briefings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS memory_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS emails ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_digests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS email_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calendar_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS file_locks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS session_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS session_handoffs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS session_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS checkpoint_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ai_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS log_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS checkpoint_summaries ENABLE ROW LEVEL SECURITY;

-- Note: service_role key bypasses RLS entirely, so no policies needed.
-- The server uses service_role, so it will continue to work without any policies.
-- This just blocks direct anon key access via PostgREST.
